###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:latest'

    mysql:
        image: 'mysql:latest'
        working_dir: /var/www
        volumes:
            - '.:/var/www'
        environment:
            - MYSQL_ROOT_PASSWORD=36gucoj1
            - MYSQL_DATABASE=lara
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=36gucoj1
        ports:
            - '3306:3306'

    webserver:
        image: 'nginx:latest'
        working_dir: /var/www
        restart: always
        volumes:
            - '.:/var/www'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './certbot/www/:/var/www/certbot/'
        ports:
            - '80:80'
            - '443:443'
    certbot:
        image: 'certbot/certbot:latest'
        volumes:
            - './certbot/www/:/var/www/certbot/'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /var/www
        volumes:
            - '.:/var/www'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
