services:
    webserver:
        image: 'nginx:latest'
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            - '/etc/letsencrypt/:/etc/letsencrypt/'
            - '.:/var/www'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - php-fpm
            - redis
            - mysql
        networks:
            - internet
            - appnet

    mysql:
        image: 'mysql:latest'
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            - '.:/var/www'
            - '/home/admin/db/lara/mysql/:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=36gucoj1
            - MYSQL_DATABASE=lara
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=36gucoj1
        networks:
            - appnet

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            - '.:/var/www'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
        depends_on:
            - mysql

        networks:
            - appnet

    redis:
        image: 'redis:latest'
        restart: unless-stopped
        networks:
            - appnet

networks:
    internet:
        name: internet
        driver: bridge
    appnet:
        name: appnet
        driver: bridge

